# Generated by Django 3.0.5 on 2020-07-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_auto_20200410_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='offer',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
